# Generated by Django 4.0.3 on 2022-03-31 13:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_alter_articles_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='articles',
            options={},
        ),
    ]
