# Generated by Django 4.0.3 on 2022-03-31 13:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_alter_articles_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articles',
            name='slug',
        ),
    ]
