# Generated by Django 4.0.3 on 2022-04-02 09:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_remove_articles_slug'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='articles',
            options={'verbose_name_plural': 'Articles'},
        ),
    ]
