# Generated by Django 4.0.3 on 2022-06-16 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='member',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
