# Generated by Django 4.0.3 on 2022-04-02 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('doc', models.FileField(upload_to='uploads/')),
                ('date_uploaded', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Documents',
            },
        ),
    ]
