# Generated by Django 4.0.3 on 2022-04-04 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='category',
            field=models.CharField(choices=[('Media Releases', 1), ('News Clippings', 2), ('Self', 3)], default=False, max_length=20),
        ),
    ]
