# Generated by Django 4.0.3 on 2022-04-06 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0002_remove_spnamember_id_alter_spnamember_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='spnamember',
            name='subscription',
            field=models.CharField(choices=[(1, 'Monthly'), (2, '6 Monthly'), (3, 'Yearly')], default=1, max_length=10),
        ),
    ]
