# Generated by Django 4.0.3 on 2022-04-07 19:12

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0003_spnamember_subscription'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='spnamember',
            name='county',
        ),
        migrations.RemoveField(
            model_name='spnamember',
            name='street_address2',
        ),
        migrations.AddField(
            model_name='spnamember',
            name='paid_until',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
