# Generated by Django 4.0.3 on 2022-04-07 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0004_remove_spnamember_county_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spnamember',
            name='paid_until',
            field=models.DateField(blank=True, null=True),
        ),
    ]
