# Generated by Django 4.0.3 on 2022-04-07 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0005_alter_spnamember_paid_until'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spnamember',
            name='subscription',
            field=models.CharField(choices=[('Monthly', '£10 monthly'), ('Six Monthly', '£55 six monthly'), ('Yearly', '£100 yearly')], default=1, max_length=16),
        ),
    ]
