# Generated by Django 4.0.3 on 2022-04-14 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0007_spnamember_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='spnamember',
            name='paid',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
