# Generated by Django 4.0.3 on 2022-04-14 20:07

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0008_spnamember_paid'),
    ]

    operations = [
        migrations.AddField(
            model_name='spnamember',
            name='stripe_id',
            field=models.CharField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
    ]
