# Generated by Django 4.0.3 on 2022-05-08 08:02

import django.contrib.auth.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0011_plan'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='plan',
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
