# Generated by Django 4.0.3 on 2022-05-08 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0013_plan_disp_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='spnamember',
            name='has_cancelled',
            field=models.BooleanField(default=False),
        ),
    ]
