# Generated by Django 4.0.3 on 2022-05-10 14:37

from django.db import migrations
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0014_spnamember_has_cancelled'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spnamember',
            name='country',
            field=django_countries.fields.CountryField(blank=True, max_length=2, null=True),
        ),
    ]
